### ISSUE TITLE
Allow joining lines without spaces

### ISSUE THREAD

**Issue by foresto** [jsabol/all-goblins-have-names#4]
An option to concatenate lines without a space in between would be useful for generating names from prefix and suffix tables.

For example, I have a table of 100 goblin name prefixes like these:

    Ark
    Az
    Balg
    Zib

And another table of 100 goblin name suffixes:

    sog
    shuk
    gad

When those tables are rolled as a pair, I currently get names like  "Ark sog" and "Az gad". I then have to manually remove the spaces. It would be nice if they weren't there in the first place.

Bonus: An option to auto-capitalize the first letter of the text would help with names, too, because then I would need only a single table of lower-case syllables instead of separate prefix and suffix tables.

**Comment by jsabol** [comment]
Unfortunately, I won't be able to support either of these features without majorly extending this module. It is impossible to enter a space as a text line in a table, because Foundry automatically trims out the space to be an empty value. So, without adding the space automatically, there would be no way for users who needed that space to add one in.

Similarly, adding options like that would need a major extension to tables generally, and cross-compatibility with those extensions with BetterTables.
